### ISSUE TITLE
Create GitHub releases

### ISSUE THREAD

**Issue by orhun** [Chleba/tui-slides#1]
I packaged `tui-slides` for the AUR: <https://aur.archlinux.org/packages/tui-slides-git> (builds from source/git)

It would be nice to create GitHub releases so that it can be packaged as non-VCS too 🐻

**Comment by Chleba** [comment]
Hi @orhun,
You are just amazing guy. Thank You so much. I made a version `v0.1.1`. Cheers :)

**Comment by orhun** [comment]
Perfect, thanks! Created another package: https://aur.archlinux.org/packages/tui-slides
